services:
  - type: web
    name: unimart-api
    env: node
    plan: free # Or your desired plan
    buildCommand: "npm install && npm run build && npm run migrate:run"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production